name: unit-tests
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**'

jobs:
  run:
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: ./
      - name: Run Unit Tests for Templater
        working-directory: config-templating
        run: |
          go test -v
      - name: Run Unit Tests for GoPinotAPI
        working-directory: ./
        run: |
          go test -v
  calculate-coverage:
    runs-on: ubuntu-latest
    needs: run
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: ./
      - name: Calculate Coverage for GoPinotAPI
        working-directory: ./
        run: |
          go test -coverprofile=coverage.out
          go tool cover -func=coverage.out
      - name: Upload to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-report: coverage.out
